name: Deploy BlueGreen Lambda

on:
  push:
    paths:
      - 'serverless-bluegreen/**'
    branches:
      - main
      - develop

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    name: Deploy to AWS (Dev)
    runs-on: ubuntu-latest
    environment: dev   # ðŸ‘ˆ usa los environment secrets de "dev"

    defaults:
      run:
        working-directory: serverless-bluegreen

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            serverless-bluegreen/package-lock.json
            serverless-bluegreen/package.json

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless (Dev)
        run: npx serverless deploy --stage dev --verbose

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to AWS (Prod)
    runs-on: ubuntu-latest
    environment: prod   # ðŸ‘ˆ usa los environment secrets de "prod"

    defaults:
      run:
        working-directory: serverless-bluegreen

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            serverless-bluegreen/package-lock.json
            serverless-bluegreen/package.json

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless (Prod)
        run: npx serverless deploy --stage prod --verbose
